In [1]:
import pandas as pd

df = pd.read_csv('../data/heart.csv')

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/heart.csv'

In [2]:
import os
os.getcwd()

'/Users/apple/Desktop/cardiac_ai_project/notebooks'

In [3]:
import pandas as pd
df = pd.read_csv('data/heart.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data/heart.csv'

In [6]:
import os
print("Current Path:", os.getcwd())
print("Files Here:", os.listdir())

Current Path: /Users/apple/Desktop/cardiac_ai_project/notebooks
Files Here: ['model_training.ipynb']

In [2]:
import pandas as pd

df = pd.read_csv('../data/heart.csv')
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [3]:

print("Shape:", df.shape)

print("Columns:", df.columns)

print("\nData Types:")
print(df.dtypes)

Shape: (920, 16)
Columns: Index(['id', 'age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs',
       'restecg', 'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='object')

Data Types:
id            int64
age           int64
sex          object
dataset      object
cp           object
trestbps    float64
chol        float64
fbs          object
restecg      object
thalch      float64
exang        object
oldpeak     float64
slope        object
ca          float64
thal         object
num           int64
dtype: object

In [4]:
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
id            0
age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
num           0
dtype: int64

In [5]:
print("\nTarget Value Counts:")
print(df['target'].value_counts())

Target Value Counts:

KeyError: 'target'

In [6]:
print(df.columns)

Index(['id', 'age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs',
       'restecg', 'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='object')

In [8]:

df['target'] = df['num'].apply(lambda x: 1 if x > 0 else 0)


print(df['target'].value_counts())

target
1    509
0    411
Name: count, dtype: int64

In [10]:
df = df.drop(columns=['id', 'dataset', 'num'])

df.head()

KeyError: "['id', 'dataset', 'num'] not found in axis"

In [11]:
print(df.columns)

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalch',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [12]:
df = df.drop(columns=['id', 'dataset', 'num'], errors='ignore')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,target
0,63,Male,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,67,Male,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,1
2,67,Male,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,37,Male,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,41,Female,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [13]:
print("Missing values per column:\n")
print(df.isnull().sum())

Missing values per column:

age           0
sex           0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
target        0
dtype: int64

In [14]:
print("\nTotal missing values:", df.isnull().sum().sum())

Total missing values: 1759

In [15]:
df.replace('?', pd.NA, inplace=True)
df.isnull().sum()

age           0
sex           0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
target        0
dtype: int64

In [16]:
df.isnull().sum().sum()

np.int64(1759)

In [17]:
import numpy as np

df.replace('?', np.nan, inplace=True)

In [18]:
df.isnull().sum().sum()

np.int64(1759)

In [19]:
df.dtypes

age           int64
sex          object
cp           object
trestbps    float64
chol        float64
fbs          object
restecg      object
thalch      float64
exang        object
oldpeak     float64
slope        object
ca          float64
thal         object
target        int64
dtype: object

In [20]:
import numpy as np

# Replace question marks (with or without spaces)
df = df.replace(r'^\s*\?\s*$', np.nan, regex=True)

# Check total missing again
df.isnull().sum().sum()

np.int64(1759)

In [21]:
num_cols = ['trestbps', 'chol', 'thalch', 'oldpeak', 'ca']

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

df.isnull().sum().sum()

np.int64(942)

In [22]:
cat_cols = ['fbs', 'restecg', 'exang', 'slope', 'thal']

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

df.isnull().sum().sum()

/var/folders/tr/03n531016kb4k3bn80cwln0m0000gn/T/ipykernel_844/458518825.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(df[col].mode()[0])

np.int64(0)

In [23]:
df = pd.get_dummies(df, drop_first=True)

df.head()

,age,trestbps,chol,fbs,thalch,exang,oldpeak,ca,target,sex_Male,cp_atypical angina,cp_non-anginal,cp_typical angina,restecg_normal,restecg_st-t abnormality,slope_flat,slope_upsloping,thal_normal,thal_reversable defect
0,63,145.0,233.0,True,150.0,False,2.3,0.0,0,True,False,False,True,False,False,False,False,False,False
1,67,160.0,286.0,False,108.0,True,1.5,3.0,1,True,False,False,False,False,False,True,False,True,False
2,67,120.0,229.0,False,129.0,True,2.6,2.0,1,True,False,False,False,False,False,True,False,False,True
3,37,130.0,250.0,False,187.0,False,3.5,0.0,0,True,False,True,False,True,False,False,False,True,False
4,41,130.0,204.0,False,172.0,False,1.4,0.0,0,False,True,False,False,False,False,False,True,True,False

In [24]:
X = df.drop('target', axis=1)
y = df['target']

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (920, 18)
y shape: (920,)

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (736, 18)
X_test: (184, 18)
y_train: (736,)
y_test: (184,)

In [27]:
from sklearn.linear_model import LogisticRegression


log_model = LogisticRegression(max_iter=1000)


log_model.fit(X_train, y_train)

print("Model trained successfully")

Model trained successfully